## Netflix Movies and Tv Shows

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
release_year,8807.0,2014.180198,8.819312,1925.0,2013.0,2017.0,2019.0,2021.0

In [7]:
df.shape

(8807, 12)

In [8]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [11]:
df[["type","title","rating"]]

         type                  title rating
0       Movie   Dick Johnson Is Dead  PG-13
1     TV Show          Blood & Water  TV-MA
2     TV Show              Ganglands  TV-MA
3     TV Show  Jailbirds New Orleans  TV-MA
4     TV Show           Kota Factory  TV-MA
...       ...                    ...    ...
8802    Movie                 Zodiac      R
8803  TV Show            Zombie Dumb  TV-Y7
8804    Movie             Zombieland      R
8805    Movie                   Zoom     PG
8806    Movie                 Zubaan  TV-14

[8807 rows x 3 columns]

In [31]:
df["duration"] = df["duration"].str.replace(",","")

In [32]:
df["duration"] = pd.to_numeric(df["duration"], errors="coerce")

In [45]:
df.groupby("title")["duration"].sum().sort_values(ascending=False).head(2).astype(int)

title
#Alive                        0
Riphagen - The Untouchable    0
Name: duration, dtype: int64

In [29]:
df[df["release_year"]>2020].sort_values("release_year",ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,NaN,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
964,s965,Movie,Things Heard & Seen,"Robert Pulcini, Shari Springer Berman","Amanda Seyfried, James Norton, Natalia Dyer, A...",NaN,"April 29, 2021",2021,NaN,121 min,"Horror Movies, Thrillers",A young woman discovers that both her husband ...
966,s967,Movie,Get the Grift,Pedro Antonio,"Marcus Majella, Samantha Schmütz, Caito Mainie...",Brazil,"April 28, 2021",2021,NaN,95 min,"Comedies, International Movies","After a botched scam, Clóvis bumps into Lohane..."
967,s968,TV Show,Headspace Guide to Sleep,NaN,Evelyn Lewis Prieto,NaN,"April 28, 2021",2021,NaN,1 Season,"Docuseries, Science & Nature TV",Learn how to sleep better with Headspace. Each...
968,s969,TV Show,Sexify,NaN,"Aleksandra Skraba, Maria Sobocińska, Sandra Dr...",Poland,"April 28, 2021",2021,NaN,1 Season,"International TV Shows, TV Comedies, TV Dramas",To build an innovative sex app and win a tech ...
...,...,...,...,...,...,...,...,...,...,...,...,...
465,s466,TV Show,Heist,NaN,NaN,NaN,"July 14, 2021",2021,NaN,1 Season,"Crime TV Shows, Docuseries",Millions in stolen cash. Missing luxury bourbo...
466,s467,TV Show,My Unorthodox Life,NaN,NaN,NaN,"July 14, 2021",2021,NaN,1 Season,Reality TV,"Follow Julia Haart, Elite World Group CEO and ..."
467,s468,Movie,Private Network: Who Killed Manuel Buendía?,Manuel Alcalá,Daniel Giménez Cacho,NaN,"July 14, 2021",2021,NaN,100 min,"Documentaries, International Movies",A deep dive into the work of renowned Mexican ...
468,s469,Movie,The Guide to the Perfect Family,Ricardo Trogi,"Louis Morissette, Émilie Bierre, Catherine Cha...",NaN,"July 14, 2021",2021,NaN,102 min,"Comedies, Dramas, International Movies","A couple in Québec deals with the pitfalls, pr..."
8437,s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,NaN,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

In [24]:
df[["type","title","duration"]]

         type                  title   duration
0       Movie   Dick Johnson Is Dead     90 min
1     TV Show          Blood & Water  2 Seasons
2     TV Show              Ganglands   1 Season
3     TV Show  Jailbirds New Orleans   1 Season
4     TV Show           Kota Factory  2 Seasons
...       ...                    ...        ...
8802    Movie                 Zodiac    158 min
8803  TV Show            Zombie Dumb  2 Seasons
8804    Movie             Zombieland     88 min
8805    Movie                   Zoom     88 min
8806    Movie                 Zubaan    111 min

[8807 rows x 3 columns]

In [43]:
df.groupby("title")["listed_in"].sum().head(5)

title
#Alive                           Horror Movies, International Movies, Thrillers
#AnneFrank - Parallel Stories               Documentaries, International Movies
#FriendButMarried                 Dramas, International Movies, Romantic Movies
#FriendButMarried 2               Dramas, International Movies, Romantic Movies
#Roxy                                                 Comedies, Romantic Movies
Name: listed_in, dtype: object